name: coka
description: A new Flutter project.
publish_to: "none"

version: 2.0.0+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  go_router: ^15.1.2
  google_sign_in: ^6.2.2
  firebase_core: ^3.10.0
  firebase_messaging: ^15.0.4
  flutter_inappwebview: ^6.1.5
  flutter_facebook_auth: ^7.1.2
  platform: ^3.1.4
  image_picker: ^1.0.7
  permission_handler: ^12.0.0+1
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  timeago: ^3.6.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_rating_bar: ^4.0.1
  infinite_scroll_pagination: ^5.0.0
  flutter_riverpod: ^2.4.9
  gap: ^3.0.1
  url_launcher: ^6.2.4
  flutter_animate: ^4.5.0
  flutter_emoji: ^2.5.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1 
  multi_select_flutter: ^4.1.3
  dropdown_search: ^6.0.1
  intl: 0.20.2
  flutter_speed_dial: ^7.0.0
  flutter_contacts: ^1.1.9+2
  syncfusion_flutter_charts: ^29.2.7
  rive: ^0.13.20
  photo_view: ^0.14.0
  awesome_dialog: ^3.1.0
  package_info_plus: ^8.3.0
  pointycastle: ^4.0.0
  http: ^1.1.0
  file_picker: ^8.0.0+1
  mime: ^1.0.4
  path: ^1.8.3
  firebase_database: ^11.1.4
  flutter_cache_manager: ^3.3.1
  crypto: ^3.0.2
  flutter_keyboard_visibility: ^6.0.0
  http_parser: any
  collection: any
  appsflyer_sdk: ^6.16.21
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  device_info_plus: ^11.5.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - shorebird.yaml

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700

flutter_native_splash: 
  image: assets/images/splash_laucher.png
  branding: assets/images/splash_laucher.png # Xoá dòng này nếu không có branding
  color: "#ffffff"
  # image_dark: assets/images/splash_logo_dark.png
  fullscreen: true
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
